version: '3.9'

services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      # Data akan disimpan secara permanen di folder chroma_data lokal
      - ./chroma_data:/data
    environment:
      - ALLOW_RESET=TRUE
    restart: unless-stopped
